spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
prue:
  empresa: mock/empresa.json
